[preview]
enable = false
x = 100
y = 200
width = 880
height = 600
zoom = 1.0

[hires]
width = 1280
height = 720

[lores]
width = 320
height = 240

[detection]
min_pixel_diff = 50

[capture]
lores = false
dir = '/home/admin/usbshare1/images/'
images = 5
anyways = 14400

[stats]
interval = 3600