[capture]
output_dir = '/home/admin/usbshare1/images/'
save_anyways_hours = 1
print_data = false
save_images = true
algorithm = "opencv"
interval = 0.5
flip = true

[preview]
enable = false
x = 100
y = 200
width = 320
height = 240
zoom = 1.0

[histogram]
min_hist_diff = 10000
width = 320
height = 240
blur = true
radius = 11
save_intermediate_images = true

[adaptive_threshold]
threshold_percent = 40
blur = false

[opencv]
preview = false

[stats]
interval = 600
