[capture]
# output_dir = '/home/admin/usbshare1/images/'
output_dir = '/home/admin/images/'
save_anyways_hours = 1
print_data = true
save_images = true
algorithm = "tflite"
interval = 0.5
flip = true
cameras = [1]   # List of cameras to pull data from and process
lores.width = 640  # TODO: Remove this. Use the algorithm specific values
lores.height = 480
process_stream = "lores"  # TODO: Remove this. Use the algorithm specific values
debug = false
save_intermediate_images = false

[tflite]
stream_to_process = "lores"
lores_width = 320
lores_height = 240
main_width = 1152
main_height = 648

[preview]
enable = true
x = 100
y = 200
width = 320
height = 240
zoom = 1.0

[histogram]
min_hist_diff = 10000
width = 320
height = 240
blur = true
radius = 11

[adaptive_threshold]
threshold_percent = 40
blur = false

[opencv]
preview = false

[stats]
interval = 600

[pir]
check_pir = false
line = 4
dwell = 0.2
