[capture]
output_dir = '/home/admin/usbshare1/images/'
# output_dir = '/home/admin/images/'                  # Output directory for
save_anyways_hours = 4                              # Save an image every n hours regardless
save_images = true                                  # Save images or dry-run
algorithm = "tflite"                                # Algorithm to use
delay = 0.5                                         # Time to sleep between iterations of the loop
flip = true                                         # Turn the camera upside down
cameras = [1]                                       # List of cameras to "watch"

[tflite]
lores_width = 320
lores_height = 240
main_width = 4608
main_height = 2592
threshold = 0.5
draw_rectangles = false                             # Draw rectangles in the buffer

[preview]
enable = false
x = 100
y = 200
width = 320
height = 240
zoom = 1.0

[stats]
interval = 600

[pir]
check_pir = true
line = 4
dwell = 0.2

[histogram]
min_hist_diff = 10000
width = 320
height = 240
blur = true
radius = 11

[adaptive_threshold]
threshold_percent = 40
blur = false
save_intermediate_images = false

[opencv]
preview = false
save_intermediate_images = false


