[preview]
enable = false
x = 100
y = 200
width = 880
height = 600
zoom = 1.0

[histogram]
min_pixel_diff = 20
width = 320
height = 240
blur = false
save_every = 1000

[capture]
output_dir = '/home/admin/usbshare1/images/'
num_images = 5
anyways = 14400
algorithm = "histogram"

[stats]
interval = 3600