[capture]
output_dir = '/home/admin/usbshare1/images/'
num_images = 5
save_anyways_hours = 4
show_data = true
save_images = false
algorithm = "histogram"
interval = 1

[preview]
enable = false
x = 100
y = 200
width = 880
height = 600
zoom = 1.0

[histogram]
min_pixel_diff = 20
width = 320
height = 240
blur = false

[stats]
interval = 3600