[capture]
output_dir = '/home/admin/usbshare1/images/'
# output_dir = '/home/admin/images/'
save_anyways_hours = 1
print_data = false
save_images = true
algorithm = "opencv"
interval = 0.5
flip = true
camera_name = 0
lores.width = 320
lores.height = 240
# main.width = 2028
# main.height = 1520
main.width = 4608
main.height = 2592
process_stream = "lores"
debug = false
save_intermediate_images = false

[preview]
enable = false
x = 100
y = 200
width = 320
height = 240
zoom = 1.0

[histogram]
min_hist_diff = 10000
width = 320
height = 240
blur = true
radius = 11

[adaptive_threshold]
threshold_percent = 40
blur = false

[opencv]
preview = false

[stats]
interval = 600
